# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class SlackCli < Formula
  desc "CLI for Slack - search messages, read threads/channels, lookup users"
  homepage "https://github.com/lox/slack-cli"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/lox/slack-cli/releases/download/v0.1.0/slack-cli_Darwin_x86_64.tar.gz"
      sha256 "27c196d45453f0af78f1258059530dc397db006adac8328369ad4987d21c5a9c"

      def install
        bin.install "slack-cli"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/lox/slack-cli/releases/download/v0.1.0/slack-cli_Darwin_arm64.tar.gz"
      sha256 "bf7d5b36e5775701621492532f0fcca2e8cbe0a74620d9edf28e3af8b8259d15"

      def install
        bin.install "slack-cli"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/lox/slack-cli/releases/download/v0.1.0/slack-cli_Linux_x86_64.tar.gz"
      sha256 "d05a95b6ff4cf7cee1fb27895d6149fc169535c801197bb1c875042d1f1aed84"
      def install
        bin.install "slack-cli"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/lox/slack-cli/releases/download/v0.1.0/slack-cli_Linux_arm64.tar.gz"
      sha256 "1ea7a4eceb454973252239583248e63b52dfc7310afa20260482967fa216ca98"
      def install
        bin.install "slack-cli"
      end
    end
  end
end
