# This file was generated by GoReleaser. DO NOT EDIT.
cask "notion-cli" do
  name "notion-cli"
  desc "CLI for Notion - search pages, read content, update pages"
  homepage "https://github.com/lox/notion-cli"
  version "0.4.1"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "notion-cli"

  on_macos do
    on_intel do
      url "https://github.com/lox/notion-cli/releases/download/v#{version}/notion-cli_Darwin_x86_64.tar.gz"
      sha256 "027bd32d7a1e4c5a68b745ccb1df61b72e489f2d6d226822f9d767cdf12149f2"
    end
    on_arm do
      url "https://github.com/lox/notion-cli/releases/download/v#{version}/notion-cli_Darwin_arm64.tar.gz"
      sha256 "ce66182e82cdff766acbe367f1101353f5bdac6a45fcfce1b47dae1422b6a5e5"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/lox/notion-cli/releases/download/v#{version}/notion-cli_Linux_x86_64.tar.gz"
      sha256 "46e77859ab50f580cdbfa918f27ac59477568443e608b05bb56ea5c855b606e6"
    end
    on_arm do
      url "https://github.com/lox/notion-cli/releases/download/v#{version}/notion-cli_Linux_arm64.tar.gz"
      sha256 "f922b8288548088e71af2c0b22bb323a6f8bf773a391762a22f1f6ff83f97c72"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/notion-cli"]
    end
  end

  # No zap stanza required
end
