# This file was generated by GoReleaser. DO NOT EDIT.
cask "notion-cli" do
  name "notion-cli"
  desc "CLI for Notion - search pages, read content, update pages"
  homepage "https://github.com/lox/notion-cli"
  version "0.1.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "notion-cli"

  on_macos do
    on_intel do
      url "https://github.com/lox/notion-cli/releases/download/v#{version}/notion-cli_Darwin_x86_64.tar.gz"
      sha256 "0420af2577c195c6fef2021660f7c4a66bfd4cd8c4593c97096322b0f702572f"
    end
    on_arm do
      url "https://github.com/lox/notion-cli/releases/download/v#{version}/notion-cli_Darwin_arm64.tar.gz"
      sha256 "2df447650d0e37bdcd56840f088a6574c45f84759d1dc206fc209b6cec3eb083"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/lox/notion-cli/releases/download/v#{version}/notion-cli_Linux_x86_64.tar.gz"
      sha256 "1236b233e5ff55d1cf9908e1bd7fffbdd61902cc69dd3748ef386b84506e4f44"
    end
    on_arm do
      url "https://github.com/lox/notion-cli/releases/download/v#{version}/notion-cli_Linux_arm64.tar.gz"
      sha256 "f0c7293b8bcbef0ed4851d03c6ef42c6149f3b7635f471d8f7aaad4d811f323b"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/notion-cli"]
    end
  end

  # No zap stanza required
end
