# This file was generated by GoReleaser. DO NOT EDIT.
cask "notion-cli" do
  name "notion-cli"
  desc "CLI for Notion - search pages, read content, update pages"
  homepage "https://github.com/lox/notion-cli"
  version "0.3.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "notion-cli"

  on_macos do
    on_intel do
      url "https://github.com/lox/notion-cli/releases/download/v#{version}/notion-cli_Darwin_x86_64.tar.gz"
      sha256 "ef2f780437c10e96a5b60a93d36973736a0841a302cc35aa91f4983d90d49491"
    end
    on_arm do
      url "https://github.com/lox/notion-cli/releases/download/v#{version}/notion-cli_Darwin_arm64.tar.gz"
      sha256 "ea1cd3050735a5e24013cdcefe009498887123c2f94d279d59f73acd03d2de2b"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/lox/notion-cli/releases/download/v#{version}/notion-cli_Linux_x86_64.tar.gz"
      sha256 "a0b6844400edeaa511cab6b0ad0e244a4db63dfa492707f685efa83d0a65c7c8"
    end
    on_arm do
      url "https://github.com/lox/notion-cli/releases/download/v#{version}/notion-cli_Linux_arm64.tar.gz"
      sha256 "28dc967a11e34637e3b7398bb6dfd39ee3a6a988eac343f85324e0efbfcd0dc1"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/notion-cli"]
    end
  end

  # No zap stanza required
end
