# This file was generated by GoReleaser. DO NOT EDIT.
cask "slack-cli" do
  name "slack-cli"
  desc "CLI for Slack - search messages, read threads/channels, lookup users"
  homepage "https://github.com/lox/slack-cli"
  version "0.4.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "slack-cli"

  on_macos do
    on_intel do
      url "https://github.com/lox/slack-cli/releases/download/v#{version}/slack-cli_Darwin_x86_64.tar.gz"
      sha256 "bec21516ef3515faf820b89450de0f0c03594ced0f681a87164d26a27fb89c81"
    end
    on_arm do
      url "https://github.com/lox/slack-cli/releases/download/v#{version}/slack-cli_Darwin_arm64.tar.gz"
      sha256 "bdaea9f58c952bec3055058fa7abb3619f16151948f0ddb15bb1e5051eb0b476"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/lox/slack-cli/releases/download/v#{version}/slack-cli_Linux_x86_64.tar.gz"
      sha256 "9bff334e672aad20aefb1d1fd0750b9cac2c29928a3d37da2477c77a366b26b7"
    end
    on_arm do
      url "https://github.com/lox/slack-cli/releases/download/v#{version}/slack-cli_Linux_arm64.tar.gz"
      sha256 "68675d443213e5d2a13190eb9b3b5db87de59d8c844ec727a00db8de14fce10b"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/slack-cli"]
    end
  end

  # No zap stanza required
end
