# This file was generated by GoReleaser. DO NOT EDIT.
cask "slack-cli" do
  name "slack-cli"
  desc "CLI for Slack - search messages, read threads/channels, lookup users"
  homepage "https://github.com/lox/slack-cli"
  version "0.1.1"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "slack-cli"

  on_macos do
    on_intel do
      url "https://github.com/lox/slack-cli/releases/download/v#{version}/slack-cli_Darwin_x86_64.tar.gz"
      sha256 "11a98901b33968be46596ff80eb0b3708c0508800e44abdc896c4663a8574420"
    end
    on_arm do
      url "https://github.com/lox/slack-cli/releases/download/v#{version}/slack-cli_Darwin_arm64.tar.gz"
      sha256 "2de5390e516f02296d34fa5fb6c62470e515229e42182738e00a848dbfeb27aa"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/lox/slack-cli/releases/download/v#{version}/slack-cli_Linux_x86_64.tar.gz"
      sha256 "e81aa3bae900945e1446278945b190dc464b2f432601cf8d15f188ffae5bba61"
    end
    on_arm do
      url "https://github.com/lox/slack-cli/releases/download/v#{version}/slack-cli_Linux_arm64.tar.gz"
      sha256 "f5e9795af4aa6b964f8bad1c7ace8fabc7161bf624068acddcc57ea5aa264760"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/slack-cli"]
    end
  end

  # No zap stanza required
end
