# This file was generated by GoReleaser. DO NOT EDIT.
cask "slack-cli" do
  version "0.5.0"

  on_macos do
    on_intel do
      sha256 "ef6b3f8b6d7f04a49a99cc5d85a13dc0cce73e518220459715c40d1a31582c59"
      url "https://github.com/lox/slack-cli/releases/download/v#{version}/slack-cli_Darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "fd38bcb344a46ce6ca2d0de5ff8dbad51df3c522f01ba7828f52aa42aaca18be"
      url "https://github.com/lox/slack-cli/releases/download/v#{version}/slack-cli_Darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "d9d9ea3a4bda7fea68e258af04c380339e41995b0f6ac89c20f58c86dc27e76c"
      url "https://github.com/lox/slack-cli/releases/download/v#{version}/slack-cli_Linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "92856ad9e735aa46031a69e4e0fdb0ca4ca32307d212d3cc942daf3705123a2c"
      url "https://github.com/lox/slack-cli/releases/download/v#{version}/slack-cli_Linux_arm64.tar.gz"
    end
  end

  name "slack-cli"
  desc "CLI for Slack - search messages, read threads/channels, lookup users"
  homepage "https://github.com/lox/slack-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "slack-cli"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/slack-cli"]
    end
  end

  # No zap stanza required

end
